# Generated by Django 3.2.6 on 2021-09-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcgscoreboard', '0002_alter_playerscore_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
