# Generated by Django 3.2.6 on 2021-09-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcgscoreboard', '0003_alter_playerscore_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
